name: Check Proofs

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache Opam
      id: cache-opam
      uses: actions/cache@v1
      with:
        path: .cache
        key: ${{ runner.os }}-opam-coq-2
    - name: install opam
      if: steps.cache-opam.outputs.cache-hit != 'true'
      run: |
        mkdir -p $GITHUB_WORKSPACE/.cache/bin
        cd $GITHUB_WORKSPACE/.cache/bin
        wget https://github.com/ocaml/opam/releases/download/2.0.6/opam-2.0.6-x86_64-linux
        mv opam-2.0.6-x86_64-linux opam
        chmod +x opam
    - name: Install coq
      if: steps.cache-opam.outputs.cache-hit != 'true'
      run: |
        export OPAMROOT=$GITHUB_WORKSPACE/.cache/.opam
        export PATH=$GITHUB_WORKSPACE/.cache/bin:$PATH
        sudo apt-get install bubblewrap
        opam init -c 4.07.1
        eval $(opam env)
        opam repo add coq-released https://coq.inria.fr/opam/released
        opam install coq -y
        coqc --version
    - name: Use coq
      run: |
        export PATH=$GITHUB_WORKSPACE/.cache/bin:$PATH
        export OPAMROOT=$GITHUB_WORKSPACE/.cache/.opam
        eval $(opam env)
        coqc --version
        cd $GITHUB_WORKSPACE
        coqc regex.v -verbose
