name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: |
        wget https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh
        sh ./opam_installer.sh $HOME/bin
        export PATH=$HOME/bin:$PATH
        opam init
        eval `opam config env`
        opam install opam-depext
        opam-depext coq
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
